Account.create!(fullname: "Admin",address: "Ninh Binh", phone: "123456789", email: "admin@gmail.com", password: "1234567",
  password_confirmation: "1234567", account_type: 1)
Account.create!(fullname: "Minh Hang",address: "Ninh Binh", phone: "123456789", email: "user1@gmail.com", password: "1234567",
  password_confirmation: "1234567", account_type: 0)
Account.create!(fullname: "Hoang Anh",address: "Ninh Binh", phone: "123456789", email: "user2@gmail.com", password: "1234567",
  password_confirmation: "1234567", account_type: 0)
Category.create!(name: "Thiết bị điện tử", parent_id: 0)
Category.create!(name: "Phụ kiện điện tử", parent_id: 0)
Category.create!(name: "Đồ chơi công nghệ", parent_id: 0)
Category.create!(name: "Apple", parent_id: 1)
Category.create!(name: "Iphone", parent_id: 1)
Category.create!(name: "SamSung", parent_id: 1)
Category.create!(name: "Kính cường lực", parent_id: 2)
Category.create!(name: "Tai nghe", parent_id: 2)
Category.create!(name: "Sạc pin", parent_id: 2)
Category.create!(name: "Kính thực tế ảo", parent_id: 3)
Category.create!(name: "Tay cầm game", parent_id: 3)
Manufacturer.create!(name: "Samsung")
Manufacturer.create!(name: "Nokia")
Manufacturer.create!(name: "HTC")
Manufacturer.create!(name: "Iphone")
Manufacturer.create!(name: "Sony")
Manufacturer.create!(name: "OOPO")
