Account.create!(fullname: "Admin",address: "Ninh Binh", phone: "123456789", email: "admin@gmail.com", password: "1234567",
  password_confirmation: "1234567", account_type: 1)
Account.create!(fullname: "Minh Hang",address: "Ninh Binh", phone: "123456789", email: "user1@gmail.com", password: "1234567",
  password_confirmation: "1234567", account_type: 0)
Account.create!(fullname: "Hoang Anh",address: "Ninh Binh", phone: "123456789", email: "user2@gmail.com", password: "1234567",
  password_confirmation: "1234567", account_type: 0)
Category.create!(name: "Device electronic", parent_id: nil)
Category.create!(name: "Electronic accessories", parent_id: nil)
Category.create!(name: "Technology toys", parent_id: nil)
Category.create!(name: "Apple", parent_id: 1)
Category.create!(name: "Iphone", parent_id: 1)
Category.create!(name: "SamSung", parent_id: 1)
Category.create!(name: "HTC", parent_id: 1)
Category.create!(name: "Sony", parent_id: 1)
Category.create!(name: "Tempered glass", parent_id: 2)
Category.create!(name: "Headphone", parent_id: 2)
Category.create!(name: "Charge", parent_id: 2)
Category.create!(name: "Virtual reality glasses", parent_id: 3)
Category.create!(name: "Game handles", parent_id: 3)
Manufacturer.create!(name: "Samsung")
Manufacturer.create!(name: "Nokia")
Manufacturer.create!(name: "HTC")
Manufacturer.create!(name: "Iphone")
Manufacturer.create!(name: "Sony")
Manufacturer.create!(name: "OOPO")
